version: "3"
services:
  wavefront_proxy:
    image: wavefronthq/proxy:4.31
    ports:
      - "2879:2879"
      - "4242:4242"
    environment:
      WAVEFRONT_URL: ${WAVEFRONT_URL}
      WAVEFRONT_TOKEN: ${WAVEFRONT_TOKEN}
      JAVA_HEAP_USAGE: 512m
    networks:
      - proxy
  backend:
    image: duboc/cdbackend:1.1
    ports:
      - "9090:9090"
    environment:
      WF_PROXY: wavefront_proxy:2879
    networks:
      - proxy
  frontend:
    image: duboc/cdfrontend:1.2
    ports:
      - "80:80"
    networks:
      - proxy
    volumes:
      - nginx_logs:/var/log/nginx
  telegraf:
    image: telegraf:1.8.3
    volumes:
      - ./telegraph/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - nginx_logs:/var/log/nginx:ro
    networks:
      - proxy

networks:
  proxy:

volumes:
  nginx_logs:
