apiVersion: apps/v1
kind: Deployment
metadata:
  name: catdogbe-deployment
  labels:
    app: catdogbe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catdogbe
  template:
    metadata:
      labels:
        app: catdogbe
    spec:
      containers:
      - name: catdogbe
        image: duboc/cdbackend:1.1
        ports:
        - containerPort: 9090
