apiVersion: v1
kind: Service
metadata:
  name: catdogbe-service
  labels:
    app: catdogbe-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: catdogbe
