apiVersion: apps/v1
kind: Deployment
metadata:
  name: catdogfe-deployment
  labels:
    app: catdogfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catdogfe
  template:
    metadata:
      labels:
        app: catdogfe
    spec:
      containers:
      - name: catdogfe
        image: duboc/cdfrontend:1.3
        ports:
        - containerPort: 80
        env:
          - name: BACKEND_URL
            value: "http://catdogbe-service/"
