apiVersion: v1
kind: ReplicationController
metadata:
  name: catdogfe
  labels:
    name: catdog-fe
    version: "latest"
    app: catdog
    tiers: catdog-fe
    stage: dev
spec:
  replicas: 2
  selector:
    type: catdog-fe
    version: v1
  template:
    metadata:
      labels:
        app: catdog
        type: catdog-fe
        version: v1
    spec:
      containers:
        - name: catdog
          image: duboc/cdfrontend:1.2
          ports:
          - containerPort: 80
          env:
          - name: CATDOG_VERSION
            value: '1.2'
          - name: PROXY_NAME
            value: wavefront-proxy
          - name: PROXY_PORT
            value: "2878"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace