apiVersion: v1
kind: Service
metadata:
  name: catdogfe-service
  labels:
    app: catdog
    stage: dev
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    type: catdog-fe