apiVersion: v1
kind: Service
metadata:
  name: catdogfe-service
  labels:
    app: catdogfe-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
    #  - name: http
    #    port: 80
    #    targetPort: 80
    #    protocol: TCP
  selector:
    app: catdogfe
