apiVersion: apps/v1
kind: Deployment
metadata:
  name: catdog-kafka-to-mongo-deployment
  labels:
    app: catdog-kafka-to-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catdog-kafka-to-mongo
  template:
    metadata:
      labels:
        app: catdog-kafka-to-mongo
    spec:
      containers:
      - name: catdog-kafka-to-mongo
        image: duboc/catdog-kafka-to-mongo:1.0
        ports:
        - containerPort: 9090
        env:
          - name: KAKFA_URL
            value: "http://kafka:9092"
          - name: MONGO_URL
            value: "mongodb://mongo:27017"
---

apiVersion: v1
kind: Service
metadata:
  name: catdog-kafka-to-mongo-service
  labels:
    app: catdog-kafka-to-mongo-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: catdog-kafka-to-mongo
